package com.kpezesha.MoneyTransfer.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Min;

/**
 * Entity class representing an Account in the money transfer system.
 * Maps to a database table and includes validation constraints.
 */
@Entity
public class Account {

    /**
     * The unique identifier for the account.
     * It is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The balance of the account.
     * Must be greater than or equal to 0 (no negative balances allowed).
     */
    @Min(0)
    private Double balance;

    /**
     * Gets the unique identifier of the account.
     *
     * @return the account ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the unique identifier of the account.
     *
     * @param id the account ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Gets the balance of the account.
     *
     * @return the account balance
     */
    public @Min(0) Double getBalance() {
        return balance;
    }

    /**
     * Sets the balance of the account.
     *
     * @param balance the account balance
     */
    public void setBalance(@Min(0) Double balance) {
        this.balance = balance;
    }
}
